# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cgLASSO_path <- function(X, Y, lambdas, xis, diag_penalty, max_iter, eps, s_max_condition, obj_counter_max, verbose) {
    .Call(`_mSSL_cgLASSO_path`, X, Y, lambdas, xis, diag_penalty, max_iter, eps, s_max_condition, obj_counter_max, verbose)
}

cgSSL_dpe <- function(X, Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, s_max_condition, obj_counter_max, verbose) {
    .Call(`_mSSL_cgSSL_dpe`, X, Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, s_max_condition, obj_counter_max, verbose)
}

cgSSL_dcpe <- function(X, Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, verbose) {
    .Call(`_mSSL_cgSSL_dcpe`, X, Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, verbose)
}

cgfstarSSL_dpe <- function(X, lower, upper, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, s_max_condition, obj_counter_max, verbose, nrep = 200L, nskp = 1L) {
    .Call(`_mSSL_cgfstarSSL_dpe`, X, lower, upper, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, s_max_condition, obj_counter_max, verbose, nrep, nskp)
}

cgfstarSSL_dcpe <- function(X, lower, upper, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, verbose, nrep = 200L, nskp = 1L) {
    .Call(`_mSSL_cgfstarSSL_dcpe`, X, lower, upper, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, verbose, nrep, nskp)
}

cgpSSL_dpe <- function(X, Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, s_max_condition, obj_counter_max, verbose, nrep = 200L, nskp = 1L) {
    .Call(`_mSSL_cgpSSL_dpe`, X, Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, s_max_condition, obj_counter_max, verbose, nrep, nskp)
}

cgpSSL_dcpe <- function(X, Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, verbose, nrep = 200L, nskp = 1L) {
    .Call(`_mSSL_cgpSSL_dcpe`, X, Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, verbose, nrep, nskp)
}

cgVARSSL_dpe <- function(Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, s_max_condition, obj_counter_max, verbose) {
    .Call(`_mSSL_cgVARSSL_dpe`, Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, s_max_condition, obj_counter_max, verbose)
}

cgVARSSL_dcpe <- function(Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, verbose) {
    .Call(`_mSSL_cgVARSSL_dcpe`, Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, verbose)
}

gSSLcpp <- function(Y, xis, eta_hyper_params, diag_penalty, max_iter, eps, obj_counter_max, verbose) {
    .Call(`_mSSL_gSSLcpp`, Y, xis, eta_hyper_params, diag_penalty, max_iter, eps, obj_counter_max, verbose)
}

mSSL_dpe <- function(X, Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, s_max_condition, obj_counter_max, verbose) {
    .Call(`_mSSL_mSSL_dpe`, X, Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, s_max_condition, obj_counter_max, verbose)
}

mSSL_dcpe <- function(X, Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, verbose) {
    .Call(`_mSSL_mSSL_dcpe`, X, Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, verbose)
}

fstarSSL_dpe <- function(X, lower, upper, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, s_max_condition, obj_counter_max, verbose, nrep = 200L, nskp = 1L) {
    .Call(`_mSSL_fstarSSL_dpe`, X, lower, upper, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, s_max_condition, obj_counter_max, verbose, nrep, nskp)
}

fstarSSL_dcpe <- function(X, lower, upper, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, verbose, nrep = 200L, nskp = 1L) {
    .Call(`_mSSL_fstarSSL_dcpe`, X, lower, upper, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, verbose, nrep, nskp)
}

mpSSL_dpe <- function(X, Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, s_max_condition, obj_counter_max, verbose, nrep = 200L, nskp = 1L) {
    .Call(`_mSSL_mpSSL_dpe`, X, Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, s_max_condition, obj_counter_max, verbose, nrep, nskp)
}

mpSSL_dcpe <- function(X, Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, verbose, nrep = 200L, nskp = 1L) {
    .Call(`_mSSL_mpSSL_dcpe`, X, Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, verbose, nrep, nskp)
}

#' scale covariance and precision in place
#' This routine will scale the covariance matrix to have unit diagonal in place and also properly scale the precision.
#' @param Sigma a matrix that is the covariance matrix, will be scaled to have unit diagonal
#' @param Omega should be the inverse of Sigma
#' @return no return, scaling will be done in place
unitdiag2 <- function(Sigma, Omega) {
    invisible(.Call(`_mSSL_unitdiag2`, Sigma, Omega))
}

